python -m src.base --seed 7777 --trial zero-one-margin_cos_tml_seed_7777_no --activation no
python -m src.base --seed 7777 --trial zero-one-margin_cos_tml_seed_7777_relu --activation relu
python -m src.base --seed 7777 --trial zero-one-margin_cos_tml_seed_7777_soft_plus --activation soft_plus
python -m src.base --seed 7777 --trial zero-one-margin_cos_tml_seed_7777_leaky_relu --activation leaky_relu
python -m src.base --seed 7777 --trial zero-one-margin_cos_tml_seed_7777_hard_swish --activation hard_swish
python -m src.base --seed 7777 --trial zero-one-margin_cos_tml_seed_7777_selu --activation selu
python -m src.base --seed 7777 --trial zero-one-margin_cos_tml_seed_7777_celu --activation celu
python -m src.base --seed 7777 --trial zero-one-margin_cos_tml_seed_7777_gelu --activation gelu
python -m src.base --seed 7777 --trial zero-one-margin_cos_tml_seed_7777_silu --activation silu
python -m src.base --seed 7777 --trial zero-one-margin_cos_tml_seed_7777_mish --activation mish

python -m src.base --seed 1225 --trial zero-one-margin_cos_tml_seed_1225_no --activation no
python -m src.base --seed 1225 --trial zero-one-margin_cos_tml_seed_1225_relu --activation relu
python -m src.base --seed 1225 --trial zero-one-margin_cos_tml_seed_1225_soft_plus --activation soft_plus
python -m src.base --seed 1225 --trial zero-one-margin_cos_tml_seed_1225_leaky_relu --activation leaky_relu
python -m src.base --seed 1225 --trial zero-one-margin_cos_tml_seed_1225_hard_swish --activation hard_swish
python -m src.base --seed 1225 --trial zero-one-margin_cos_tml_seed_1225_selu --activation selu
python -m src.base --seed 1225 --trial zero-one-margin_cos_tml_seed_1225_celu --activation celu
python -m src.base --seed 1225 --trial zero-one-margin_cos_tml_seed_1225_gelu --activation gelu
python -m src.base --seed 1225 --trial zero-one-margin_cos_tml_seed_1225_silu --activation silu
python -m src.base --seed 1225 --trial zero-one-margin_cos_tml_seed_1225_mish --activation mish